apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: docker.io/mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Redhat@123
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql/data
  volumes:
    - name: mysql-volume
      persistentVolumeClaim:
        claimName: pvc-claim

