apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-read-bind
  namespace: k8s-testing
subjects:
- kind: User
  name: "docker-desktop"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: list-pod
  apiGroup: rbac.authorization.k8s.io

